# docker-compose EXEMPLE
redis:
 image: redis:latest
web:
 build: .
 command: daphne -b 0.0.0.0 -p 8000 multichat.asgi:channel_layer
 volumes:
  - .:/code
 ports:
  - "8000:8000"
 links:
  - redis
worker:
 build: .
 command: python manage.py runworker
 volumes:
  - .:/code
 links:
  - redis

  # scaling the workers is just that easy:
    # docker-compose scale worker=3
